#服务器端口号配置
server:
  port: 8080

# 配置alipay数据
alipay:
  # 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  APPID: 9021000133618870
  # 商户私钥，您的PKCS8格式RSA2私钥
  RSA_PRIVATE_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+ix3NtBeh9qXYY7oNLzq538gdxRu2rpOgSuaxoQ8lPkgOmRQ6mOScD/7uO9VR5df9igW4Ss5HYvS7CqcD0SQjFmpLXVg4CLHYbMO+EVRvimAF73QsGfRD75IMcJibR+rgfGv0+YMyFRyIp0K+jTmCFhZrLyESqfZMo+qNuN4rFjWoHnQJtHvVb5xCHl+lMLpgEFp20iTPJ1dIC5bAu4NofFHbGEPuMQjb3E/surd0lFtZmD5PIv7OocLVZkC0lMZ7A7EUpDHYAaAOjumgM62M78IzDUvvbufjqXbiJKf7RzQIrvILB4hkp+t8i+5UEMN/EY/X7fM9Jmm4Ck74niU5AgMBAAECggEBAI3ih7niTerEAHDmqechcShx09EfMmjRDIrC25APr3h7LSr5oE+WBD2Vx65cjZdjgHeCbInz4jDUJgqVfxJfjPo3ucUO6B8pkkzniMainu5D6wbgbPBeDz77SRTMT0bpwaOR4s3Tcnc7sziq3A+Kl/UfP2hm+sisGQSu1nzb2UvY/pSU1y60HazB9Fks7ovPAEYhjo0kpBuuI30t8fuJ5klMlKcQ3vydfdTqCaotlnfm/SorxYIuEy1kmb+J23gxUj8Fyrqsx9wWa288NzRyrQuRsh/Dy19tZvqeomNyGsYpG8FTfmUu4ZA/vgq3YG0DBtAcnibdwQwyPkIlnzc+5qUCgYEA8oHlsuN/Hucd4zU7Ezx1qv0Gqg1+jgZ+sTNY2vqCrAgz2/gPJr5H/tn+qD3Ofi6n9kD8c3MQro+UPp3vzqOUVIBl36kFg1k2xF0pbbMotU8jiUJTJZj37YhKq3xtpEMI2c8ohjGQ6irocFGqKBAADbXfk2oqwmnsuUcGshb1XiMCgYEAySUUxlsAJHdDO8D9ggcZLgGA8YNoWGTXLD2IzunmOJGy+gJgYKVAP4HLs2wYYnnthbwQBnEPPNA8j1z8592eyt9VOQnBwz+S6g7IrKvwG8/U3n1szheC24hS0tXfZT+EeTGPh4nYszPsbPGZ1TmPke94uA1zPsonYl8bCIv+rvMCgYB83uo6DO6eKP+4yOYcZ5tnalaOJdiupSWDdR8h0rCKiMa7U6Xpmz1TO0jntLupObj/EkNr5yoF2KTLAWREEPMF9/99BXlzQvLydc4pUIF7qr5vpRlPWM8BHpbkanPCi0n5bbQ+NTObgHCjtUlay7JbXPU84QQXi5d7Z9lIxo2d5QKBgCy0pydm9mMkdrcDL9UEit4ky2niUQDEeOaGTq/eYKLWDzdt68nPMLZsvL+GGO1aOCZvJAiqfD6B8dPTUQqfwTlJ5gElYAFrUdXfr05hcJ5d1OwWaGZt51GvvOjLTDmOonzlPQdc5eL+eV/FWvF/N5+x39zYcHLWL2a3yKRfqR1tAoGBAIUQUbaWI5IvfKVGyln2ZkIqUk+sdLf0jeUj1C9AcZUyg5p1e9XxrR5UHG+yvL3Ib5+0Y35KXD7S7upNUMKrIirqLDnEu79a1tg2rTcmo5VOARYlnLE82QCegac29xZ55vVVKu+tS1vfL6M/oNFPJKfe5D962ZOpUFFPoyX/uIVa
  # 支付宝支付公钥
  ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu4dHgz+Ynq4pRUHO2SkD/EbRHPPElW9rFqmLY1c0trSx3B6tXJn865LkzPZb9JaBa3Ke3fqnUwTdhzu1pi/TjnfT6tAwOeTeRmKLtPUNhieBOh3WGRSkhaA0xmSN35bbNWLxKaTF34MNI5QBr768YKTrJw4Pz8RdhJ7K1XvnowNKkG4jDrnZdqDQ0FdrWzjbxa2mfDTBMbZpDZu7ZLial5VEbuxuuWvIGn/D+cQ2XWiwKxzajXZfkJ6Jkce+tcmIFtZ8ainOx/Bpma8/bDz18FxM/Jh/ETdovDAr7SpmGYqb54J3Yp3/bbwtaACLxj9vWMf+eFLuZYv6sD0IJy7MowIDAQAB
  # 异步回调地址 必须外网能够访问（这里需要配置内网穿透），当支付成功后会调用该API
  notify_url: http://hpzekg.natappfree.cc/alipay/pay/callback
  # 同步回调地址 必须外网能够访问
  return_url:
  # 网关（注意沙箱网关和正式网关的区别，这里填写沙箱环境下的网关）
  URL: https://openapi.alipaydev.com/gateway.do
  # 编码
  CHARSET: UTF-8
  # 返回数据格式
  FORMAT: json
  # 日志地址
  log_path: /log
  # RSA2
  SIGNTYPE: RSA2